workflows:
  android:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - flutter pub get
      - flutter clean
      - flutter build appbundle --release
    artifacts:
      - build/app/outputs/**/*.aab
