name: freefire_world
description: Freefire World starter app
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.18.0
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.8.0
  google_sign_in: ^6.1.0
  shared_preferences: ^2.1.1

flutter:
  uses-material-design: true
